module.exports = {
    EMAIL_REQUIRED: 'User email is required',
    EMAIL_NOT_VALID: 'Invalid user email',
    PWD_NOT_MATCH: 'Password and Confirm Password does not match',
    DUPLICATE_USER: 'This user already exists, please try again with a different email',
    BRAND_NAME_REQUIRED: 'Brand name is required',
    BRAND_WEBSITE_REQUIRED: 'Brand website is required',
    BRAND_ID_REQUIRED: 'Brand id is required',
    UNATHORIZED: 'Unauthorised',
    USER_NOT_FOUND: 'User not found!',
    PASSWORD_REQUIRED: 'User password is required',
    USER_TYPE_REQUIRED: 'User type required',
    WRONG_OLD_PASSWORD_REQUIRED: 'Wrong password',
    NAME_REQUIRED: 'Name is required',
    PRIMARY_ADDRESS_REQUIRED: 'Primary address is required',
    PHONE_REQUIRED: 'Phone is required',
    NEW_PASSWORD_REQUIRED: 'New password is required',
    CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
    SHIPING_LIMITS_REQUIRED: 'Shipping limits required',
    RETAILER_ID_REQUIRED: 'Retailer id is required',
    FIRST_NAME_REQUIRED: 'First name required',
    LAST_NAME_REQUIRED: 'Last name required',
    USER_ROLE_REQUIRED: 'User role is required',
    INVALID_REQUEST: 'Invalid request data',
    DELETED_SUCCESSFULLY: 'Deleted successfully',
    ADMIN_ROLE_VALIDATE: 'In order to remove Administrator privileges, there needs to be at least one other user set as Administrator',
    USER_ID_REQUIRED: 'User id is required'
};
